### ISSUE TITLE
fid scan still not working properly

### ISSUE THREAD

**Issue by Bkaribo** [Bridge12Technologies/OpenVnmrJ_B12T#38]
branch: master
starting the fid scan creates one fid (FID scan) then no updates appear
the FID is not properly scaled and it cannot be interacted with - no new experiment can be started until the acquisition server is restarted

**Comment by DanIverson** [comment]
Can you run, in a terminal window,
  ps -ef | grep Expproc
to get the PID of the Expproc process. Then run
  sudo strace -o bout -s 128  -t -p <PID_of_Expproc>
and then start the Fid scan. After it fails, send me the bout file.

**Comment by Bkaribo** [comment]
Hi dan,

this is the b12out for the fid scan, currently the MPS gets a firmware
update so the other issue will have to wit

Karl

On Fri, Aug 11, 2023 at 4:01 PM Dan Iverson ***@***.***> wrote:
>
> Can you run, in a terminal window,
> ps -ef | grep Expproc
> to get the PID of the Expproc process. Then run
> sudo strace -o bout -s 128 -t -p <PID_of_Expproc>
> and then start the Fid scan. After it fails, send me the bout file.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>



-- 
Karl Rieger

***@***.***
Bridge 12 Technologies, Inc.
11 Michigan Dr Ste 2, Natick, MA 01760

-- 
**********************************************
Bridge12 Technologies, Inc.
11 Michigan Drive Ste 2

Natick, MA 01760, USA

Web: 
http://www.bridge12.com <http://www.bridge12.com/>
**********************************************

This email and any files 
transmitted with it
are company confidential, meant for the sole
use of the 
intended recipient. Any use or
dissemination of this email by others is 
strictly
prohibited. If you are not the intended recipient,
please contact 
the sender immediately.

**Comment by DanIverson** [comment]
OpenVnmrJ_B12T has a script to update the MPS firmware.
See OpenVnmrJ_B12T/firmware/uploadFirmware
